table! {
    policies (policy_id) {
        policy_id -> Integer,
        policy_sha256 -> Char,
        policy_name -> Varchar,
        max_file_attempts -> Unsigned<Bigint>,
        max_item_attempts -> Unsigned<Bigint>,
        max_fn_attempts -> Unsigned<Bigint>,
        max_ty_attempts -> Unsigned<Bigint>,
        max_stmt_attempts -> Unsigned<Bigint>,
        max_expr_attempts -> Unsigned<Bigint>,
        num_item_dist -> Varchar,
        item_dist -> Text,
        type_dist -> Text,
        prim_type_dist -> Text,
        num_stmt_dist -> Varchar,
        stmt_dist -> Text,
        mutability_prob -> Double,
        expr_dist -> Text,
        bool_true_prob -> Double,
        otherwise_if_stmt_prob -> Double,
        max_if_else_depth -> Unsigned<Bigint>,
        max_block_depth -> Unsigned<Bigint>,
        max_arith_depth -> Unsigned<Bigint>,
        max_expr_depth -> Unsigned<Bigint>,
        max_composite_depth -> Unsigned<Bigint>,
        array_length_dist -> Varchar,
        default_array_type_dist -> Text,
        new_array_prob -> Double,
        max_array_depth -> Unsigned<Bigint>,
        max_expr_depth_in_array -> Unsigned<Bigint>,
        tuple_length_dist -> Varchar,
        default_tuple_type_dist -> Text,
        new_tuple_prob -> Double,
        max_tuple_depth -> Unsigned<Bigint>,
        max_expr_depth_in_tuple -> Unsigned<Bigint>,
        struct_length_dist -> Varchar,
        default_struct_type_dist -> Text,
        field_struct_prob -> Double,
        field_struct_copy_prob -> Double,
        tuple_struct_copy_prob -> Double,
        max_struct_depth -> Unsigned<Bigint>,
        max_expr_depth_in_struct -> Unsigned<Bigint>,
        binary_op_dist -> Text,
        unary_op_dist -> Text,
        new_lifetime_prob -> Double,
        disable_lifetime -> Bool,
        created_at -> Timestamp,
        updated_at -> Timestamp,
    }
}

table! {
    runs (run_id) {
        run_id -> Integer,
        git_hash -> Char,
        version -> Varchar,
        hostname -> Varchar,
        seed -> Unsigned<Bigint>,
        success -> Bool,
        reviewed -> Bool,
        policy_id -> Integer,
        generation_duration_in_millis -> Nullable<Unsigned<Bigint>>,
        rustfmt_duration_in_millis -> Nullable<Unsigned<Bigint>>,
        total_sub_runs -> Unsigned<Bigint>,
        expected_checksum -> Nullable<Decimal>,
        statistics -> Nullable<Text>,
        error_kind -> Nullable<Varchar>,
        error_message -> Nullable<Text>,
        run_timeout -> Unsigned<Bigint>,
        generate_timeout -> Unsigned<Bigint>,
        compile_timeout -> Unsigned<Bigint>,
        rustfmt_timeout -> Unsigned<Bigint>,
        created_at -> Timestamp,
        updated_at -> Timestamp,
    }
}

table! {
    statistics (run_id) {
        run_id -> Integer,
        gen_success_statistics_id -> Integer,
        gen_failure_statistics_id -> Integer,
        program_statistics_id -> Integer,
        max_failed_item_depth -> Unsigned<Bigint>,
        max_failed_stmt_depth -> Unsigned<Bigint>,
        max_failed_expr_depth -> Unsigned<Bigint>,
        max_failed_ty_depth -> Unsigned<Bigint>,
        word_count -> Unsigned<Bigint>,
        line_count -> Unsigned<Bigint>,
        created_at -> Timestamp,
        updated_at -> Timestamp,
    }
}

table! {
    statistics_map (statistics_map_id) {
        statistics_map_id -> Integer,
        total_items -> Nullable<Unsigned<Bigint>>,
        total_stmts -> Nullable<Unsigned<Bigint>>,
        total_exprs -> Nullable<Unsigned<Bigint>>,
        total_tys -> Nullable<Unsigned<Bigint>>,
        total_binary_ops -> Nullable<Unsigned<Bigint>>,
        total_unary_ops -> Nullable<Unsigned<Bigint>>,
        item_struct -> Nullable<Unsigned<Bigint>>,
        item_function -> Nullable<Unsigned<Bigint>>,
        stmt_local -> Nullable<Unsigned<Bigint>>,
        stmt_semi -> Nullable<Unsigned<Bigint>>,
        stmt_expr -> Nullable<Unsigned<Bigint>>,
        expr_literal -> Nullable<Unsigned<Bigint>>,
        expr_binary -> Nullable<Unsigned<Bigint>>,
        expr_unary -> Nullable<Unsigned<Bigint>>,
        expr_cast -> Nullable<Unsigned<Bigint>>,
        expr_if -> Nullable<Unsigned<Bigint>>,
        expr_block -> Nullable<Unsigned<Bigint>>,
        expr_ident -> Nullable<Unsigned<Bigint>>,
        expr_assign -> Nullable<Unsigned<Bigint>>,
        expr_index -> Nullable<Unsigned<Bigint>>,
        expr_field -> Nullable<Unsigned<Bigint>>,
        expr_reference -> Nullable<Unsigned<Bigint>>,
        ty_unit -> Nullable<Unsigned<Bigint>>,
        ty_prim -> Nullable<Unsigned<Bigint>>,
        ty_tuple -> Nullable<Unsigned<Bigint>>,
        ty_array -> Nullable<Unsigned<Bigint>>,
        ty_struct -> Nullable<Unsigned<Bigint>>,
        ty_reference -> Nullable<Unsigned<Bigint>>,
        binary_op_add -> Nullable<Unsigned<Bigint>>,
        binary_op_sub -> Nullable<Unsigned<Bigint>>,
        binary_op_mul -> Nullable<Unsigned<Bigint>>,
        binary_op_div -> Nullable<Unsigned<Bigint>>,
        binary_op_and -> Nullable<Unsigned<Bigint>>,
        binary_op_or -> Nullable<Unsigned<Bigint>>,
        binary_op_bit_xor -> Nullable<Unsigned<Bigint>>,
        binary_op_bit_and -> Nullable<Unsigned<Bigint>>,
        binary_op_bit_or -> Nullable<Unsigned<Bigint>>,
        binary_op_eq -> Nullable<Unsigned<Bigint>>,
        binary_op_lq -> Nullable<Unsigned<Bigint>>,
        binary_op_le -> Nullable<Unsigned<Bigint>>,
        binary_op_ne -> Nullable<Unsigned<Bigint>>,
        binary_op_ge -> Nullable<Unsigned<Bigint>>,
        binary_op_gt -> Nullable<Unsigned<Bigint>>,
        binary_op_wrapping_add -> Nullable<Unsigned<Bigint>>,
        binary_op_wrapping_sub -> Nullable<Unsigned<Bigint>>,
        binary_op_wrapping_mul -> Nullable<Unsigned<Bigint>>,
        binary_op_wrapping_div -> Nullable<Unsigned<Bigint>>,
        binary_op_wrapping_rem -> Nullable<Unsigned<Bigint>>,
        binary_op_wrapping_shl -> Nullable<Unsigned<Bigint>>,
        binary_op_wrapping_shr -> Nullable<Unsigned<Bigint>>,
        unary_op_deref -> Nullable<Unsigned<Bigint>>,
        unary_op_not -> Nullable<Unsigned<Bigint>>,
        unary_op_neg -> Nullable<Unsigned<Bigint>>,
        created_at -> Timestamp,
        updated_at -> Timestamp,
    }
}

table! {
    sub_runs (sub_run_id) {
        sub_run_id -> Integer,
        run_id -> Integer,
        compiler_name -> Varchar,
        opt -> Char,
        version -> Varchar,
        success -> Bool,
        compilation_duration_in_millis -> Nullable<Unsigned<Bigint>>,
        run_duration_in_micros -> Nullable<Unsigned<Bigint>>,
        checksum -> Nullable<Decimal>,
        error_kind -> Nullable<Varchar>,
        error_message -> Nullable<Text>,
        created_at -> Timestamp,
        updated_at -> Timestamp,
    }
}

joinable!(runs -> policies (policy_id));
joinable!(sub_runs -> runs (run_id));

allow_tables_to_appear_in_same_query!(
    policies,
    runs,
    statistics,
    statistics_map,
    sub_runs,
);
