CREATE TABLE runs (
    run_id INTEGER AUTO_INCREMENT,
    git_hash VARCHAR(255) NOT NULL,
    version VARCHAR(255) NOT NULL,
    hostname VARCHAR(255) NOT NULL,
    seed BIGINT UNSIGNED NOT NULL,
    success BOOLEAN NOT NULL,
    policy_id INTEGER NOT NULL,
    statistics TEXT,
    error VARCHAR(255),
#     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
#     updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (run_id)
);

CREATE TABLE policies (
   policy_id INTEGER AUTO_INCREMENT,
   policy_sha256 BIGINT NOT NULL,
   name VARCHAR(255) NOT NULL,
   max_file_attempts BIGINT UNSIGNED NOT NULL,
   max_item_attempts BIGINT UNSIGNED NOT NULL,
   max_fn_attempts BIGINT UNSIGNED NOT NULL,
   max_ty_attempts BIGINT UNSIGNED NOT NULL,
   max_stmt_attempts BIGINT UNSIGNED NOT NULL,
   max_expr_attempts BIGINT UNSIGNED NOT NULL,
   num_item_dist VARCHAR(255) NOT NULL,
   item_dist TEXT NOT NULL,
   type_dist TEXT NOT NULL,
   prim_type_dist TEXT NOT NULL,
   num_stmt_dist VARCHAR(255) NOT NULL,
   stmt_dist TEXT NOT NULL,
   mutability_prob DOUBLE NOT NULL,
   expr_dist TEXT NOT NULL,
   bool_true_prob DOUBLE NOT NULL,
   otherwise_if_stmt_prob DOUBLE NOT NULL,
   max_if_else_depth BIGINT UNSIGNED NOT NULL,
   max_block_depth BIGINT UNSIGNED NOT NULL,
   max_arith_depth BIGINT UNSIGNED NOT NULL,
   max_expr_depth BIGINT UNSIGNED NOT NULL,
   array_length_dist VARCHAR(255) NOT NULL,
   default_array_type_dist TEXT NOT NULL,
   new_array_prob DOUBLE NOT NULL,
   max_array_depth BIGINT UNSIGNED NOT NULL,
   max_expr_depth_in_array BIGINT UNSIGNED NOT NULL,
   tuple_length_dist VARCHAR(255) NOT NULL,
   default_tuple_type_dist TEXT NOT NULL,
   new_tuple_prob DOUBLE NOT NULL,
   max_tuple_depth BIGINT UNSIGNED NOT NULL,
   max_expr_depth_in_tuple BIGINT UNSIGNED NOT NULL,
   struct_length_dist VARCHAR(255) NOT NULL,
   default_struct_type_dist TEXT NOT NULL,
   field_struct_prob DOUBLE NOT NULL,
   field_struct_copy_prob DOUBLE NOT NULL,
   tuple_struct_copy_prob DOUBLE NOT NULL,
   max_struct_depth BIGINT UNSIGNED NOT NULL,
   max_expr_depth_in_struct BIGINT UNSIGNED NOT NULL,
   binary_op_dist TEXT NOT NULL,
   unary_op_dist TEXT NOT NULL,
   new_lifetime_prob DOUBLE NOT NULL,
   disable_lifetime BOOLEAN NOT NULL,
#    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
#    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (policy_id)
);